### ISSUE TITLE
Empty `Type` column with a width of "85%"

### ISSUE THREAD

**Issue by jonnyreeves** [phtrivier/grunt-junit-report#1]
Thanks for creating this library - just what I was after :+1:   FWIW I am using it in conjunction with https://github.com/sbrandwoo/grunt-qunit-junit

I noticed that the XSD contains a "Type" column for each individual test case which has a default width of 85% (therefore dominating the table!), however I can't see where this field is ever populated form the Junit Report XML

I assume you copied the XSD from the ANT task's resources, however, do you think it would be a good idea to drop this column (or at least the 85% width rule) - or is my Junit XML just formatted wrong (it's really hard to find good examples)

**Comment by phtrivier** [comment]
Thanks very much, I'm glad the library is usefull to you ! 

The "Type" column is actually used to display the error details when a test fails. 

In the xsd, there is thise rule :

```
<!-- method header -->
<xsl:template name="testcase.test.header">
    <tr valign="top">
        <th>Name</th>
        <th>Status</th>
        <th width="80%">Type</th>
        <th nowrap="nowrap">Time(s)</th>
    </tr>
</xsl:template>
```

And this one : 

```
<xsl:template match="testcase" mode="print.test">
    <tr valign="top">
        <xsl:attribute name="class">
            <xsl:choose>
                <xsl:when test="failure | error">Error</xsl:when>
            </xsl:choose>
        </xsl:attribute>
        <td><xsl:value-of select="@name"/></td>
        <xsl:choose>
            <xsl:when test="failure">
                <td>Failure</td>
                <td><xsl:apply-templates select="failure"/></td>
            </xsl:when>
            <xsl:when test="error">
                <td>Error</td>
                <td><xsl:apply-templates select="error"/></td>
            </xsl:when>
            <xsl:when test="skipped">
                <td>Skipped</td>
                <td><xsl:apply-templates select="skipped"/></td>
            </xsl:when>
            <xsl:otherwise>
                <td>Success</td>
                <td></td>
            </xsl:otherwise>
        </xsl:choose>
        <td>
            <xsl:call-template name="display-time">
                <xsl:with-param name="value" select="@time"/>
            </xsl:call-template>
        </td>
    </tr>
</xsl:template>
```

So as you can see, if the test case has no error, in the table, you get this (which is rather ugly, I agree :) 

<table>
<tr>
<th>Status</th>
<th>Type</th>
</tr>
<tr>
<td>Success</td>
<td></td>
</tr>
</table>

But if you test has an error, you'll have something like : 

<table>
<tr>
<th>Status</th>
<th>Type</th>
</tr>
<tr>
<td>Failure</td>
<td>Expected false to be true</td>
</tr>
</table>

And the "Type" column can become very big if your tests error have stack traces, which is why (I assume) the width is hardcoded.

As a matter of fact, I _did_ copy-paste the XSD from junit-report ant task, and I'm probably not going to touch then too much. 
But as usual, PRs are welcomed !

Cheers
